version: '3.8'
services:
  web:
    build: .
    ports:
      - "5030:80"  # Host:Container port mapping
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDBSettings__ConnectionString=mongodb://mongo:27017
      - MongoDBSettings__DatabaseName=CarRentalDB
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: